"""
Out-of-band config bootstrap for the Elyon-Sol deployment (C1 / VL-081).

Generates the trust material the three services need and writes it to deploy/.env
(git-ignored, never committed):
  - a gate Ed25519 signing keypair (the gate signs with the private half; the
    target pins the public half),
  - the pinned-root anchor (sha256 of the committed published record the
    publisher serves and the target anchor-verifies).

The generated config is INTERNALLY CONSISTENT by construction: the public key the
target pins corresponds to the gate's signing key, and the anchor matches the
served record - so an envelope signed by the gate verifies at the target. That
round-trip is checked by TESTS/deploy/test_bootstrap_config.py (C1's sandbox-green
referent). The docker orchestration itself is UNVALIDATED in the sandbox (no
docker); standing it up is the author's (artifact 13 C1, locus AUTHOR).

This module performs NO crypto secrecy beyond generating an ephemeral key; the
private key is written to .env for the operator and is never committed (deploy/
.env is git-ignored). Secure distribution of the pinned anchor itself remains the
named G5 floor.

Run:  python deploy/bootstrap_config.py   # writes deploy/.env
"""

import os
import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

# Importable so the round-trip test can build a config without writing a file.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from IMPLEMENTATION.published_source import anchor_sha256  # noqa: E402

DEFAULT_RECORD = "EVIDENCE/published_hashes.json"
DEFAULT_TARGET_URL = "http://target:9000/target"
DEFAULT_PUBLISHER_URL = "http://publisher:9100/published_hashes.json"


def build_config(record_path=DEFAULT_RECORD, target_url=DEFAULT_TARGET_URL,
                 publisher_url=DEFAULT_PUBLISHER_URL, key_id="gate-deploy-001"):
    """Generate a fresh, internally-consistent deployment config. Returns a dict of
    the ELYON_* environment values the three services read. The gate's
    SIGNING_KEY_ID and the target's GATE_KEY_ID are the same id by construction."""
    priv = Ed25519PrivateKey.generate()
    priv_hex = priv.private_bytes_raw().hex()
    pub_hex = priv.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw).hex()
    with open(record_path, "rb") as f:
        pinned_root = anchor_sha256(f.read())
    return {
        # gate (pep)
        "ELYON_SIGNING_KEY_HEX": priv_hex,
        "ELYON_SIGNING_KEY_ID": key_id,
        "ELYON_DECISION_MAX_AGE_SECONDS": "300",
        # target (reference_target) - pins the gate public key + the anchor
        "ELYON_GATE_KEY_ID": key_id,
        "ELYON_GATE_PUBLIC_KEY_HEX": pub_hex,
        "ELYON_PINNED_ROOT_SHA256": pinned_root,
        "ELYON_TARGET_URL": target_url,
        "ELYON_PUBLISHER_URL": publisher_url,
    }


def render_env(config):
    header = ("# Elyon-Sol deployment config (generated by deploy/bootstrap_config.py).\n"
              "# Out-of-band trust material - DO NOT COMMIT (deploy/.env is git-ignored).\n")
    body = "".join("%s=%s\n" % (k, v) for k, v in config.items())
    return header + body


def main():
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    config = build_config()
    with open(out, "w", encoding="ascii", newline="\n") as f:
        f.write(render_env(config))
    print("wrote", out)
    print("  ELYON_SIGNING_KEY_ID     =", config["ELYON_SIGNING_KEY_ID"])
    print("  ELYON_GATE_PUBLIC_KEY_HEX=", config["ELYON_GATE_PUBLIC_KEY_HEX"])
    print("  ELYON_PINNED_ROOT_SHA256 =", config["ELYON_PINNED_ROOT_SHA256"])
    print("  (private signing key written to .env; never commit it)")


if __name__ == "__main__":
    main()
